image:
  file: .gitpod.Dockerfile
ports: 
- port: 5900
  onOpen: ignore
- port: 6000
  onOpen: open-preview
tasks:
- init: pip3 install -r requirements.txt
# - command: cd Racing_Game/Racing_Game_Against_Trained_AI
- command: python Racing_Game/Racing_Game_Against_Trained_AI/main.py
